### PR TITLE
[18.0][MIG] fs_attachment: Migration to 18.0

### PR DESCRIPTION
**Pull request by qgroulard**
- [x] depends on #399

Including commits from https://github.com/OCA/storage/pull/402

### CODE REVIEW

**Comment by sbidoul** [comment]
@qgroulard there is a handful of commits to grab from #402

**Review by sbidoul — APPROVED** [review]
Code review.

**Comment by lmignon** [comment]
@qgroulard Can you rebase. #399 is merged.

**Review by lmignon — APPROVED** [review]
Code review

**Pull request merged**
