### PR TITLE
[ADD] attachment_db_by_checksum

### PR DESCRIPTION
**Pull request by SirTakobi**
Third attempt to share this module with the OCA ecosystem, after the previous attempts have gone _stale_:

1. for `10.0`: https://github.com/OCA/storage/pull/109
2. for `12.0`: https://github.com/OCA/storage/pull/107

Here I am preserving the history of https://github.com/OCA/storage/pull/107 (following https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0), and have added a few goodies:

- refactoring
- improved documentation (method docstrings)
- **tests** :tada:
- fix a particular use-case (see the [FIX] commit for more details)

Hoping the _third time's a charm_ :four_leaf_clover:

### CODE REVIEW

**Comment by SirTakobi** [comment]
Is any of the previous reviewers still interested? @gurneyalex @simahawk
cc @eLBati

**Review by eLBati — APPROVED** [review]
Thanks

**Comment by SirTakobi** [comment]
@OCA/storage-maintainers maybe someone is interested in this module?

**Review by simahawk — APPROVED** [review]
I guess this is used in prod since a while now, right? :)

**Pull request merged**
