### PR TITLE
[17.0][FW] fs_storage: forward port v16 changes

### PR DESCRIPTION
**Pull request by sbidoul**
Forward port #317, #320, #334, #336, #357, #385

### CODE REVIEW

**Comment by sbidoul** [comment]
All clean cherry-picks except the change to USAGE.md which I had to manually convert from USAGE.rst.

**Comment by sbidoul** [comment]
I manually compared with 16.0 using `pip-wheel-diff "odoo-addon-fs_storage==16.*" git+https://github.com/oca/storage@refs/pull/397/head#subdirectory=fs_storage`, it looks complete.

**Review by rvalyi — APPROVED** [review]
LGTM (code review, no test)

**Comment by lmignon** [comment]
@sbidoul you missed https://github.com/OCA/storage/pull/400/commits/dd626455dfcd80003818f8123811e8d9eabfe861

**Comment by sbidoul** [comment]
@lmignon it was in https://github.com/OCA/storage/pull/396

**Review by lmignon — APPROVED** [review]
Checked that all changes in 16.0 are included into this PR. Thank you!

**Comment by lmignon** [comment]
I canceled the merge process. Waiting for feedback from #384

**Pull request merged**
