### PR TITLE
PIN fsspec requirement because change in make_path_posix() signature

### PR DESCRIPTION
**Pull request by bealdav**
https://github.com/fsspec/filesystem_spec/pull/1567/files#diff-b47117e431a1b37790be709fb84c0d854da5e73203e3de57ec6b6032b18eebf1R280

spec

### CODE REVIEW

**Comment by bealdav** [comment]
cc @lmignon @benwillig

**Review by lmignon — CHANGES_REQUESTED** [review]
@bealdav What's the problem?  I would prefer to adapt the code to the new version than being locked to a specific version. Moreover, the version constrain should be specified into the manifest file.

**Comment by bealdav** [comment]
Yes you're right. This PR is just a quick alert for community

**Comment by lmignon** [comment]
@bealdav can you take a look at https://github.com/OCA/storage/pull/372

**Comment by bealdav** [comment]
Thanks to warned me, perfect

**Pull request closed without merging**
