### PR TITLE
[15.0][storage_session_redis] New module

### PR DESCRIPTION
**Pull request by robyf70**
Add a new module to store odoo sessions on Redis

### CODE REVIEW

**Review by andreampiovesana — COMMENTED** [review]
is better if you redo a PR in server-tools ?

**Comment by robyf70** [comment]
@pedrobaeza Do you have any thought keeping it on this repo or move to ``server-tools`` and indeed the possibility to get it merged?

**Comment by pedrobaeza** [comment]
Checking its contents, and not depending on nothing of this repo, I would put it in server-auth, with the name `auth_session_redis_storage`.

About the merge, you need at least 2 reviewers, one of them being a PSC. You can review other PRs in the repository, and ask in exchange that they review yours.

Check also if there's something similar, as this Redis thing is not the first time that had been commented.

**Comment by robyf70** [comment]
> Checking its contents, and not depending on nothing of this repo, I would put it in server-auth, with the name `auth_session_redis_storage`.
> 
> About the merge, you need at least 2 reviewers, one of them being a PSC. You can review other PRs in the repository, and ask in exchange that they review yours.
> 
> Check also if there's something similar, as this Redis thing is not the first time that had been commented.

@pedrobaeza Why ``server-auth`` since the module doesn't have anything related to authentication, it's just session storage?

**Comment by pedrobaeza** [comment]
Isn't the authenticated session what you are storing?

**Comment by robyf70** [comment]
> Isn't the authenticated session what you are storing?

It's storing ``werkzeug``'s session data. By default odoo uses a file per session. The module support session autoexpire and redis cluster as well.

**Comment by simahawk** [comment]
What about https://github.com/camptocamp/odoo-cloud-platform/tree/16.0/session_redis ?
This is running on prod since version 8.0.

**Comment by robyf70** [comment]
> What about https://github.com/camptocamp/odoo-cloud-platform/tree/16.0/session_redis ? This is running on prod since version 8.0.

The module looks good

**Pull request closed without merging**
