### PR TITLE
[14.0][FW] storage_s3: fix aws regions lookup to load once

### PR DESCRIPTION
**Pull request by hailangvn**
* This is to forward port #87

Every time the selection field was loaded
S3 API were called to retrieve regions.
This can have a big impact on computing URLs
and in any case is useless if we assume
that regions do not change every now and then.

### CODE REVIEW

**Review by simahawk — APPROVED** [review]

**Comment by simahawk** [comment]
@OCA-git-bot what the heck are you saying? :smile: 

/ocabot merge patch

**Comment by simahawk** [comment]
@gurneyalex @sbidoul do you understand why the bot refuses to merge? I'm pretty sure I have enough rights :smile:

**Comment by sbidoul** [comment]
@simahawk try again please. Probably a token permissions issue.

**Pull request merged**
