### PR TITLE
[13.0] [IMP] storage_backend_ftp

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Fix connection problem for implicit FTP over TLS
@ForgeFlow

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
Hi @acsonefho 

We are modifying your original code to connect over TLS, it seemed to cover an explicit FTP over TLS connection. You included a comment in the code:

`# Due to a bug into between ftplib and ssl, this part (about ssl) might not work!`

That makes me think that you haven't used the connection over TLS functionality, can you confirm?. Assuming so, we have changed the approach to  use implicit FTP over TLS. 

Is this change fine with you? or maybe it was really working for you, so in such case we should add a new ftp_encryption option to have FTP, implicit FTPS and explicit FTPS to cover all 3 cases.

What do you think?

**Comment by acsonefho** [comment]
> Hi @acsonefho
> 
> We are modifying your original code to connect over TLS, it seemed to cover an explicit FTP over TLS connection. You included a comment in the code:
> 
> `# Due to a bug into between ftplib and ssl, this part (about ssl) might not work!`
> 
> That makes me think that you haven't used the connection over TLS functionality, can you confirm?. Assuming so, we have changed the approach to use implicit FTP over TLS.
> 
> Is this change fine with you? or maybe it was really working for you, so in such case we should add a new ftp_encryption option to have FTP, implicit FTPS and explicit FTPS to cover all 3 cases.
> 
> What do you think?

Feel free to edit what is necessary :)

**Review by LoisRForgeFlow — APPROVED** [review]
Functional review, works as expected :+1:

**Comment by LoisRForgeFlow** [comment]
@OCA/storage-maintainers can you check this? It seems that the author of the module in v13 and the contributor migrating it to v14 did not really used FTPS, so I guess this PR is good to go.

**Comment by LoisRForgeFlow** [comment]
@simahawk can you help getting this merge? Thanks!

**Review by simahawk — APPROVED** [review]
LG

**Comment by simahawk** [comment]
/ocabot merge minor

To be fwd ported I guess?

**Comment by LoisRForgeFlow** [comment]
> /ocabot merge minor
> 
> To be fwd ported I guess?

Indeed, @JasminSForgeFlow could you forward port this?

**Pull request merged**
