### PR TITLE
[13.0][storage_image_product] add tag_id to kanban view

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
image

### CODE REVIEW

**Review by HviorForgeFlow — APPROVED** [review]
It does not hurt to see the tags on that kanban view, nice improve :+1: IMO

**Comment by MiquelRForgeFlow** [comment]
This PR is targeting v14 instead of v13. Are you sure?

**Comment by JordiBForgeFlow** [comment]
@MiquelRForgeFlow fixed

**Comment by JordiBForgeFlow** [comment]
Added also the variant attribute values to the kanban view:

image

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by HviorForgeFlow — APPROVED** [review]

**Pull request merged**
