### PR TITLE
[17.0][IMP] fs_attachment: send the mimetype information for S3

### PR DESCRIPTION
**Pull request by vincent-hatakeyama**
Port of #354

### CODE REVIEW

**Comment by vincent-hatakeyama** [comment]
Applied suggested changes https://github.com/OCA/storage/pull/354#discussion_r1654223924

**Review by lmignon — COMMENTED** [review]
@vincent-hatakeyama I didn't see my [suggested changes](https://github.com/OCA/storage/pull/354#discussion_r1654223924) into thIs PR. Do I miss something?

**Comment by vincent-hatakeyama** [comment]
> @vincent-hatakeyama I didn't see my [suggested changes](https://github.com/OCA/storage/pull/354#discussion_r1654223924) into thIs PR. Do I miss something?

Apparently forgot to add the changes or something similar. That’s fixed now.

**Comment by vincent-hatakeyama** [comment]
The Odoo failure is unrelated to these changes; I have the error when running those tests in an image without any  non odoo core modules.

**Review by lmignon — APPROVED** [review]

**Comment by sbidoul** [comment]
heads-up, in #497 this is moving to a separate fs_attachment_s3 module

**Pull request merged**
