### PR TITLE
[17.0][MIG] fs_base_multi_image + fs_product_multi_image: Migration to 17.0

### PR DESCRIPTION
**Pull request by nguyenminhchien**
Ref: BSRD-747

Depends:

- [ ] https://github.com/OCA/storage/pull/348
- [ ] https://github.com/OCA/storage/pull/345

### CODE REVIEW

**Review by gurneyalex — APPROVED** [review]

**Review by lmignon — APPROVED** [review]
Thank you for the migration!

**Comment by lmignon** [comment]
@nguyenminhchien Can you rebase and remove test dependency on merged PR plz? Thank you.

**Comment by nguyenminhchien** [comment]
> @nguyenminhchien Can you rebase and remove test dependency on merged PR plz? Thank you.

Hi, updated.

**Comment by dreispt** [comment]
Attempting merge with #369

**Pull request closed without merging**
