### PR TITLE
[15.0][FIX] storage_backend: avoid singleton error

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
Forward port of #243

### CODE REVIEW

**Comment by simahawk** [comment]
@LoisRForgeFlow can you open a separated PR w/ the copier update?

**Comment by LoisRForgeFlow** [comment]
@simahawk Sure: https://github.com/OCA/storage/pull/247

**Review by hparfr — APPROVED** [review]

**Comment by LoisRForgeFlow** [comment]
@simahawk Rebased after the fix in the CI :)

**Pull request merged**
