### PR TITLE
[12.0][IMP] storage_image - add some fields in the views

### PR DESCRIPTION
**Pull request by hparfr**

### CODE REVIEW

**Comment by hparfr** [comment]
ping @thibaultrey  @sebastienbeau

**Review by sebastienbeau — APPROVED** [review]
LGTM code review

**Comment by hparfr** [comment]
Please wait before merging, I need to check something before;

**Comment by hparfr** [comment]
It's ready now.

**Review by PierrickBrun — APPROVED** [review]
Nice addition, please fix black

**Pull request merged**
