### PR TITLE
[13.0][FIX] storage_image_product: take available attributes from the line value_ids

### PR DESCRIPTION
**Pull request by JordiMForgeFlow**

### CODE REVIEW

**Comment by JordiMForgeFlow** [comment]
CC @HviorForgeFlow

**Review by HviorForgeFlow — APPROVED** [review]

**Review by JaumeBforgeFlow — APPROVED** [review]

**Review by GuillemCForgeFlow — APPROVED** [review]
LGTM 👍🏽

**Review by HviorForgeFlow — APPROVED** [review]
Makes totally sense!

**Comment by JordiMForgeFlow** [comment]
Any chance we could get this merged @sebastienbeau @simahawk ? Thank you :)

**Review by MiquelRForgeFlow — APPROVED** [review]

**Pull request merged**
