### PR TITLE
[14.0] Sync and switch to GH actions

### PR DESCRIPTION
**Pull request by simahawk**

### CODE REVIEW

**Review by hparfr — APPROVED** [review]

**Comment by simahawk** [comment]
`storage_image_product_brand (LGPL-3) depends on product_brand (AGPL-3)`

Which one do we change? :)

**Comment by simahawk** [comment]
Companion PR https://github.com/OCA/brand/pull/117

**Comment by simahawk** [comment]
https://github.com/OCA/brand/pull/118

**Comment by simahawk** [comment]
@hparfr can you check https://github.com/OCA/brand/pull/118 pls ?

**Comment by sebastienbeau** [comment]
@simahawk you can move back storage_image_product_brand to AGPL-3.

AGPL-3 is more restrictive, but also protect us (as OpenSource contributor, by forcing other to contribute)
a good reading (GNU do not recommend to use LGPL anymore https://www.gnu.org/licenses/why-not-lgpl.en.html#top)

**Comment by simahawk** [comment]
Done here https://github.com/OCA/storage/pull/207

**Pull request merged**
