### PR TITLE
[15.0][MIG] storage_image

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

Depends on:

- https://github.com/OCA/storage/pull/189

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
@JasminSForgeFlow I just rebased to restart build, sorry

**Review by JuanyDForgeflow — APPROVED** [review]
LGTM!

**Comment by AaronHForgeFlow** [comment]
rebased again

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by etobella — APPROVED** [review]

**Pull request merged**
