### PR TITLE
[MIG] fs_storage: Migration to 18.0

### PR DESCRIPTION
**Pull request by qgroulard**
Including commits from https://github.com/OCA/storage/pull/397

### CODE REVIEW

**Comment by sbidoul** [comment]
/ocabot migration fs_storage

Can you cherry-pick the commits from #397 ?

**Review by lmignon — APPROVED** [review]

**Review by lmignon — APPROVED** [review]
Code review only, no tests

**Comment by sbidoul** [comment]
Rebased to pick-up the dotfiles update. The new xml autoformatter cleaned up one xml file a bit.

**Pull request merged**
