### PR TITLE
[10.0][FIX] __manifest__: Uses github repo url as website and add OCA into …

### LINKED ISSUE #1: invalid website key in manifests
Hi, the `website` key in many manifests of this repo is incorrect. This prevents uploading the packages to PyPI.

### PR DESCRIPTION
**Pull request by lmignon**
…author

fixes #1
backport of #2

### CODE REVIEW

**Review by astirpe — APPROVED** [review]

**Comment by sebastienbeau** [comment]
I close it as it already included by this PR that have been merged https://github.com/OCA/storage/pull/17

**Pull request closed without merging**
