### PR TITLE
[13.0][IMP] storage_image_product: Limit attribute value selection according with available product attributes

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
CC @ForgeFlow

### CODE REVIEW

**Review by mariadforgeflow — APPROVED** [review]
LGTM!

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Comment by MiquelRForgeFlow** [comment]
Forward ported in https://github.com/OCA/storage/pull/185.

**Comment by simahawk** [comment]
Guys, please, take the habit of making shorter commit message. The description of the change is meant to stay in the.... description of the commit. Also, if you do this properly you get a proper PR title and a proper PR description automatically.
Thanks! :pray:

**Pull request merged**
