### PR TITLE
[16.0][MIG] storage_file

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Migration

CC @ForgeFlow

### CODE REVIEW

**Comment by HviorForgeFlow** [comment]
When downloading data from a File size is set as title by default:
image

Any insight on this?

**Comment by simahawk** [comment]
> When downloading data from a File size is set as title by default: image
> 
> Any insight on this?

I think you must provide a filename field on the data field

**Comment by HviorForgeFlow** [comment]
Ready to test

**Review by ChrisOForgeFlow — APPROVED** [review]
LGTM

**Comment by lmignon** [comment]
@HviorForgeFlow Can you fix the conflicts so I can proceed to the merge. Sorry for the delay.

Regards

**Pull request merged**
