### PR TITLE
[13.0][IMP] storage_image_product: display attribute_value_ids using many2many_tags widget

### PR DESCRIPTION
**Pull request by JordiMForgeFlow**
Simple change to make it more usable for the user.

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
:+1:

**Review by ChrisOForgeFlow — APPROVED** [review]
+1

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by sebastienbeau** [comment]
Thanks for the improvement

**Pull request merged**
