### PR TITLE
[IMP] use notebook for a better UI

### PR DESCRIPTION
**Pull request by sebastienbeau**
Improve UI
depend on 
- [x] https://github.com/OCA/brand/pull/87

### CODE REVIEW

**Comment by sebastienbeau** [comment]
@simahawk @ivantodorovich @PierrickBrun

**Review by ivantodorovich — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]
@sebastienbeau Could you rebase ?

**Comment by sebastienbeau** [comment]
not need of rebase I just relaunch teh CI as dependency have been merged

**Review by simahawk — APPROVED** [review]

**Pull request merged**
