### PR TITLE
[13.0][IMP] storage_image_product: Remove image attributes unlinked from product template

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
CC @ForgeFlow 

- [x] Add migration script to cleanup dangling product image attributes

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by MiquelRForgeFlow — APPROVED** [review]
You can mark the box in your initial post.

**Review by simahawk — APPROVED** [review]
LG. FWD port to v14?

**Comment by simahawk** [comment]
@HviorForgeFlow next time pls the commit msg short. Ex: `s_image_product: clean image on product attr values delete` or similar. Then you can put a long desc into the commit description. :wink:

**Comment by HviorForgeFlow** [comment]
@simahawk pre-commit is broken. I had several PR in v13 in same status, can you guide me to solve it?

**Comment by simahawk** [comment]
here? https://github.com/OCA/oca-addons-repo-template/issues/80

**Comment by JordiMForgeFlow** [comment]
Hi @HviorForgeFlow and @simahawk 

Pre-commit is already green now :)

**Pull request merged**
