### PR TITLE
[14.0][MIG] storage_import_image_advanced

### PR DESCRIPTION
**Pull request by i-vyshnevska**
migrate https://github.com/OCA/storage/pull/113

### CODE REVIEW

**Review by simahawk — APPROVED** [review]
LG

**Review by gurneyalex — APPROVED** [review]

**Comment by simahawk** [comment]
@i-vyshnevska pls squash :pray:

**Comment by sebastienbeau** [comment]
@i-vyshnevska  can you rebase please ?

**Comment by i-vyshnevska** [comment]
> @i-vyshnevska can you rebase please ?

@sebastienbeau rebased yesterday, thanks for checking

**Comment by sebastienbeau** [comment]
oups sorry, I didn't read the log correctly
thanks
/ocabot merge patch

**Pull request merged**
