### PR TITLE
[15.0] [MIG] storage_image_product

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

Depends on:

- https://github.com/OCA/storage/pull/190

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
Please cherry-pick 92f51ac0f80ad08c227c581f77a3546a871a4d7a :)

**Comment by JasminSForgeFlow** [comment]
> Please cherry-pick [92f51ac](https://github.com/OCA/storage/commit/92f51ac0f80ad08c227c581f77a3546a871a4d7a) :)

Cherry pick done,
Thanks

**Review by mariadforgeflow — APPROVED** [review]
LGTM!

**Comment by MiquelRForgeFlow** [comment]
@JasminSForgeFlow please rebase in order to fix runboat

**Comment by JasminSForgeFlow** [comment]
> @JasminSForgeFlow please rebase in order to fix runboat

Its already up to date

**Comment by MiquelRForgeFlow** [comment]
@sbidoul how can we rerun runboat in cases like this where the branch is already rebased up to date?

**Comment by sbidoul** [comment]
@MiquelRForgeFlow the only ways to trigger a build is to push/rebase, or to use the API: https://runboat.odoo-community.org/docs#/api/trigger_pull_api_v1_builds_trigger_pr_post

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by LoisRForgeFlow** [comment]
@OCA/storage-maintainers this one seems to be ready to merge.

**Pull request merged**
