### PR TITLE
[MIG][15.0] storage_backend_sftp

### PR DESCRIPTION
**Pull request by i-vyshnevska**
depends on https://github.com/OCA/storage/pull/145

### CODE REVIEW

**Comment by SilvioC2C** [comment]
@i-vyshnevska I took the liberty to rebase the branch to fix a conflict in file `requirements.txt`

**Comment by SilvioC2C** [comment]
@i-vyshnevska I believe we can drop commit [2b920ba](https://github.com/OCA/storage/pull/148/commits/2b920ba0964a27f82649f675cda8a451ec7c85da), since #145 has been merged.

**Comment by i-vyshnevska** [comment]
> @i-vyshnevska I took the liberty to rebase the branch to fix a conflict in file `requirements.txt`

that is why I open PR's on c2c repository :wink:

**Comment by SilvioC2C** [comment]
@i-vyshnevska you're right, I'm sorry, I was in a hurry for a release and didn't think of opening a PR

**Review by simahawk — APPROVED** [review]

**Review by ivantodorovich — APPROVED** [review]

**Comment by i-vyshnevska** [comment]
@simahawk  ready for merge

**Pull request merged**
