### PR TITLE
storage_image_product: add wizard to migrate product images

### PR DESCRIPTION
**Pull request by simahawk**
Comes from a post init hook by @lmignon 
Not really tested yet.

### CODE REVIEW

**Review by lmignon — COMMENTED** [review]
Thank you @simahawk I'll try to test it in the coming days.

**Comment by rousseldenis** [comment]
@simahawk What's the status of this ?

**Comment by simahawk** [comment]
@rousseldenis currently not used on our side. It's a nice to have (of must have for existing instances w/ images) and if someone could test and write tests it would be nice. I'd keep it open or reference it in an issue.

**Comment by lmignon** [comment]
@rousseldenis This one provide a wizard that can be used to migrate existing product images when the addon is installed on an existing DB. It should be finalized.... but as always that require some times to do it.

**Comment by codeagencybe** [comment]
Is this feature working and available? 
And does it only migrate images or also other attachments from records?

**Comment by lmignon** [comment]
@codeagencybe This feature is only available into the branch linked to the PR. The wizard performs the migration of the product.template's images only.

**Pull request closed without merging**
