### PR TITLE
[17.0][FIX] fs_attachment: fix constraint

### PR DESCRIPTION
**Pull request by astirpe**
Fixes https://github.com/OCA/storage/issues/362

### CODE REVIEW

**Review by lmignon — COMMENTED** [review]
@astirpe Thank you for the proposal. Can you add some comments into the code to explain why it's done as is and do the same into the commit message.

**Comment by astirpe** [comment]
@lmignon done, could you check?

**Review by lmignon — APPROVED** [review]

**Review by gbrito — APPROVED** [review]

**Review by gurneyalex — APPROVED** [review]

**Comment by hparfr** [comment]
@astirpe can you please rebase ?

**Comment by astirpe** [comment]
@hparfr @gurneyalex rebased, thanks!

**Review by hparfr — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
