### PR TITLE
[13.0] Add move_files / find_files features

### PR DESCRIPTION
**Pull request by simahawk**
Tests collateral changes in this commit https://github.com/OCA/storage/commit/a8ef4dc6ca1b721b9084a8241bc18e4d0bc44a6e
Mainly makes test classes more clear (eg: do not inherit tests, run them explicitly, test permissions explicitly, etc).

### CODE REVIEW

**Review by lmignon — COMMENTED** [review]
:heart: Thank you @simahawk  LGTM (Code review)
Can you take a look to pre-commit error. (A little one...)
image

**Comment by simahawk** [comment]
ops, missed it! Should be fine now.

**Review by lmignon — APPROVED** [review]
Code review

**Review by sebastienbeau — APPROVED** [review]
LGTM code review

**Comment by pedrobaeza** [comment]
I'm afraid we have exhausted the Travis new rate limits for free accounts, so we need to rethink the CI across OCA.

**Pull request merged**
