### PR TITLE
[MIG] storage_backend_s3: Migration to 12.0 + improvements

### PR DESCRIPTION
**Pull request by simahawk**
Includes and superseeds #13

### CODE REVIEW

**Comment by sbidoul** [comment]
LGTM

**Comment by simahawk** [comment]
I've refactored and improved S3 handling. Tests DO PASS when not using VCRpy: calling our S3 storage straight works smoothly. Using VCRpy fails like this:

`botocore.exceptions.HTTPClientError: An HTTP Client raised and unhandled exception: a bytes-like object is required, not 'str'`

I don't get why :/

**Comment by simahawk** [comment]
This is the issue https://github.com/kevin1024/vcrpy/issues/474
I'll give a try to proposed fix.

**Comment by simahawk** [comment]
I was able to re-register VCRpy cassettes with this fix https://github.com/kevin1024/vcrpy/pull/488

**Comment by simahawk** [comment]
@sbidoul @lmignon can you pass by for a review? I've managed to fix tests by fixing vcrpy.
I added a temporary dependency on my branch here https://github.com/OCA/storage/pull/14/commits/591ff8326fb86a0e8a3010e001586b0c6e859142.
Runbot is still crazy, I'm ignoring it.

**Comment by simahawk** [comment]
dropped TMP commit, upgraded vcrpy

**Review by lmignon — APPROVED** [review]

**Comment by simahawk** [comment]
@sbidoul can you pass by again and merge if you like it? :innocent:

**Comment by lmignon** [comment]
Do we know why runbot is failling?

**Comment by simahawk** [comment]
is not failing, is in warning state but it's impossible to get to logs as they go 404 https://runbot2-2.odoo-community.org/runbot/static/build/3394509-14-7d7dd5/logs/job_20_test_all.txt
I asked Alex to have a look at it last week but he had no time.

**Comment by lmignon** [comment]
@simahawk OK, proceeding to merge...

**Pull request merged**
