### PR TITLE
[14.0] [CHG] storage: Use more permissive licence: AGPL-> LGPL

### PR DESCRIPTION
**Pull request by simahawk**
- [x] Includes #105 (to be merged 1st).

FWD port of https://github.com/OCA/storage/pull/93 (only last commit)

### CODE REVIEW

**Review by mmequignon — COMMENTED** [review]
why this change? is it planned to work in some other context with more restrictive licenses?

**Comment by simahawk** [comment]
> why this change? is it planned to work in some other context with more restrictive licenses?

follow the links between PRs and you get to https://github.com/OCA/edi/pull/343 ;)
In any case, yes, of course, the idea is to give freedom.

**Review by mmequignon — APPROVED** [review]

**Review by ivantodorovich — APPROVED** [review]

**Comment by ivantodorovich** [comment]
@simahawk can we merge this?

**Pull request merged**
