### PR TITLE
[15.0][UPD] repo template

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
@simahawk Tests seem to be failing anyway

**Comment by simahawk** [comment]
I've got the same here https://github.com/OCA/connector-interfaces/actions/runs/4313081580/jobs/7524433938

**Comment by simahawk** [comment]
Seems an issue w/ outdated pyopenssl.

Current version is 19.0.0

https://github.com/OCA/connector-interfaces/actions/runs/4313081580/jobs/7524433938#step:4:177

We should upgrade it but it's pinned by odoo and there's an old PR here https://github.com/odoo/odoo/pull/95782

**Comment by simahawk** [comment]
Results of my tests: https://github.com/OCA/connector-interfaces/pull/94#issuecomment-1451678234

**Comment by simahawk** [comment]
Funny thing: is passing here https://github.com/OCA/server-ux/pull/608 :thinking:

**Comment by simahawk** [comment]
@LoisRForgeFlow can you fix pre-commit?

**Comment by simahawk** [comment]
```
 Traceback (most recent call last):
  File "/opt/odoo/odoo/service/server.py", line 1210, in load_server_wide_modules
    odoo.modules.module.load_openerp_module(m)
  File "/opt/odoo/odoo/modules/module.py", line 396, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/opt/odoo/addons/web/__init__.py", line 4, in <module>
    from . import controllers
  File "/opt/odoo/addons/web/controllers/__init__.py", line 4, in <module>
    from . import main
  File "/opt/odoo/addons/web/controllers/main.py", line 34, in <module>
    from odoo.addons.base.models.ir_qweb import render as qweb_render
  File "/opt/odoo/odoo/addons/base/__init__.py", line 5, in <module>
    from . import models
  File "/opt/odoo/odoo/addons/base/models/__init__.py", line 23, in <module>
    from . import ir_mail_server
  File "/opt/odoo/odoo/addons/base/models/ir_mail_server.py", line 19, in <module>
    from OpenSSL import crypto as SSLCrypto
  File "/opt/odoo-venv/lib/python3.8/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/opt/odoo-venv/lib/python3.8/site-packages/OpenSSL/crypto.py", line 1553, in <module>
    class X509StoreFlags(object):
  File "/opt/odoo-venv/lib/python3.8/site-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
```

I think the issue might come from another dependency:

```
cryptography>=3.3->paramiko->odoo-addon-storage_backend_sftp<15.1dev,>=15.0dev->-r test-requirements.txt (line 6)) (1.15.1)
Requirement already satisfied: soupsieve>1.2 in /opt/odoo-venv/lib/python3.8/site-packages (from beautifulsoup4->ofxparse->odoo<15.1dev,>=15.0a->-r test-requirements.txt (line 7)) (2.4)
Requirement already satisfied: pycparser in /opt/odoo-venv/lib/python3.8/site-packages (from cffi>=1.12->cryptography>=3.3->paramiko->odoo-addon-storage_backend_sftp<15.1dev,>=15.0dev->-r test-requirements.txt (line 6)) (2.21)
Installing collected packages: odoo-test-helper, pyyaml, cachetools, bcrypt, pynacl, cryptography, paramiko, odoo-addon-server-environment, odoo-addon-queue_job, odoo-addon-component, odoo-addon-storage-backend, odoo-addon-component_event, odoo-addon-storage_backend_sftp, odoo-addon-connector
  Attempting uninstall: cryptography
    Found existing installation: cryptography 2.6.1
    Uninstalling cryptography-2.6.1:
      Successfully uninstalled cryptography-2.6.1
```

@sbidoul I've seen you faced this problem before, here https://github.com/OCA/server-auth/pull/429
In my tests on https://github.com/OCA/connector-interfaces/pull/94 I solved it w/
```
pyopenssl==20.0.0
cryptography==35.0.0
```

so when I see this https://github.com/odoo/odoo/pull/99829 I'm perplexed... 

Also, can't we enforce this for all our builds? We could avoid pinning on all modules (which is more detailed, of course, but... you know... laziness... :stuck_out_tongue_winking_eye: ).

**Comment by simahawk** [comment]
Trying here https://github.com/OCA/storage/pull/248

**Comment by simahawk** [comment]
#248 is green now. I wait for a while for a review otherwise I fast track it since it's blocking many PRs out there :)

**Pull request closed without merging**
