### PR TITLE
[13.0][MIG] storage_backend 

### PR DESCRIPTION
**Pull request by Laurent-Corron**
- [x] requires [component](https://github.com/OCA/connector/pull/355)

### CODE REVIEW

**Comment by lmignon** [comment]
cc @simahawk @rousseldenis @Cedric-Pigeon

**Review by simahawk — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by Cedric-Pigeon — APPROVED** [review]
code review

**Pull request merged**
