### PR TITLE
[13.0][storage_image_product][fix] sort order to calculate the default image

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Fixes the sort order of images in the product template and variant, used
to compute the default image displayed in the product.

image

### CODE REVIEW

**Comment by simahawk** [comment]
this seems similar/related to https://github.com/OCA/storage/pull/74/

**Comment by simahawk** [comment]
@JordiBForgeFlow @MiquelRForgeFlow if you've done this work in the ctx of shopinvader would you mind checking this PR https://github.com/shopinvader/odoo-shopinvader/pull/877?
I'd like to know if there's anything else to take care of for images re-computation. Maybe in your project you have something else that requires the trigger.

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by HviorForgeFlow — APPROVED** [review]
:+1:

**Comment by simahawk** [comment]
@JordiBForgeFlow FYI I'm going to refactor this a bit on https://github.com/OCA/storage/pull/94 because we should not store URLs we should store image/thumbs relations instead.

/ocabot merge patch

**Pull request merged**
