### PR TITLE
[12.0] storage_file: fix error creating a new file

### PR DESCRIPTION
**Pull request by hparfr**

### CODE REVIEW

**Comment by hparfr** [comment]
@sebastienbeau

**Review by sebastienbeau — APPROVED** [review]
LGTM (code review)

**Review by simahawk — DISMISSED** [review]

**Review by simahawk — APPROVED** [review]

**Comment by simahawk** [comment]
@hparfr can you squash your commits and name the module name? 
The final commit should be something like the PR title now (w/ version is ok).

I'll block the bot till then.

**Comment by simahawk** [comment]
dammit, I missed when it started :sob: 

@hparfr next time pls try to keep the commit messages clean and clear :pray: Merci! :)

**Comment by hparfr** [comment]
@simahawk Thanks !

Next time, I will try the "!fixup add tests" commit messages instead.

**Pull request merged**
